//! Dual-dialect schema migrations (`docs/DESIGN.md` §4b).
//!
//! One ordered list of migrations, each carrying the SQL for both dialects. Every
//! backend applies the steps it hasn't yet recorded in `schema_meta`, so SQLite
//! and Postgres stay in lockstep from a single source of truth.

/// One migration step, with the SQL for each supported engine.
pub struct Migration {
    pub version: i64,
    pub sqlite: &'static str,
    pub postgres: &'static str,
}

/// The ordered migration list. Append new steps; never edit an applied one.
pub const MIGRATIONS: &[Migration] = &[
    Migration {
        version: 1,
        sqlite: SQLITE_V1,
        postgres: POSTGRES_V1,
    },
    // V2 — versioning: refs (branches/tags/HEAD) and workspace config. The SQL is
    // identical across dialects (plain TEXT columns).
    Migration {
        version: 2,
        sqlite: V2,
        postgres: V2,
    },
    // V3 — merge: recorded conflicts and git-LFS-style exclusive file locks.
    Migration {
        version: 3,
        sqlite: V3,
        postgres: V3,
    },
    // V4 — attribution: actors, sessions, tool-call audit, the edit-op log, and
    // per-file line authorship. Dialects differ only in the identity columns.
    Migration {
        version: 4,
        sqlite: V4_SQLITE,
        postgres: V4_POSTGRES,
    },
];

const V2: &str = "
CREATE TABLE IF NOT EXISTS ref(
    name  TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS config(
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
";

const V3: &str = "
CREATE TABLE IF NOT EXISTS conflict(
    path TEXT PRIMARY KEY,
    kind TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS file_lock(
    path        TEXT PRIMARY KEY,
    owner       TEXT NOT NULL,
    acquired_at BIGINT NOT NULL
);
";

const V4_SQLITE: &str = "
CREATE TABLE IF NOT EXISTS actor(
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    kind                TEXT NOT NULL,
    display_name        TEXT NOT NULL,
    auth_subject        TEXT,
    agent_model         TEXT,
    agent_vendor        TEXT,
    controller_actor_id INTEGER,
    created_at          INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS session(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    actor_id   INTEGER NOT NULL,
    client     TEXT,
    started_at INTEGER NOT NULL,
    ended_at   INTEGER
);
CREATE TABLE IF NOT EXISTS tool_calls(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id   INTEGER,
    actor_id     INTEGER,
    name         TEXT NOT NULL,
    parameters   TEXT,
    result       TEXT,
    error        TEXT,
    started_at   INTEGER NOT NULL,
    completed_at INTEGER NOT NULL,
    duration_ms  INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS edit_op(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id   INTEGER,
    actor_id     INTEGER NOT NULL,
    tool_call_id INTEGER,
    ino          INTEGER NOT NULL,
    path         TEXT NOT NULL,
    op           TEXT NOT NULL,
    byte_start   INTEGER NOT NULL,
    byte_len     INTEGER NOT NULL,
    pre_hash     TEXT,
    post_hash    TEXT,
    ts           INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_edit_op_actor ON edit_op(actor_id);
CREATE INDEX IF NOT EXISTS idx_edit_op_session ON edit_op(session_id);
CREATE TABLE IF NOT EXISTS line_blame(
    ino  INTEGER PRIMARY KEY,
    runs TEXT NOT NULL
);
";

const V4_POSTGRES: &str = "
CREATE TABLE IF NOT EXISTS actor(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind                TEXT NOT NULL,
    display_name        TEXT NOT NULL,
    auth_subject        TEXT,
    agent_model         TEXT,
    agent_vendor        TEXT,
    controller_actor_id BIGINT,
    created_at          BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS session(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id   BIGINT NOT NULL,
    client     TEXT,
    started_at BIGINT NOT NULL,
    ended_at   BIGINT
);
CREATE TABLE IF NOT EXISTS tool_calls(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT,
    actor_id     BIGINT,
    name         TEXT NOT NULL,
    parameters   TEXT,
    result       TEXT,
    error        TEXT,
    started_at   BIGINT NOT NULL,
    completed_at BIGINT NOT NULL,
    duration_ms  BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS edit_op(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT,
    actor_id     BIGINT NOT NULL,
    tool_call_id BIGINT,
    ino          BIGINT NOT NULL,
    path         TEXT NOT NULL,
    op           TEXT NOT NULL,
    byte_start   BIGINT NOT NULL,
    byte_len     BIGINT NOT NULL,
    pre_hash     TEXT,
    post_hash    TEXT,
    ts           BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_edit_op_actor ON edit_op(actor_id);
CREATE INDEX IF NOT EXISTS idx_edit_op_session ON edit_op(session_id);
CREATE TABLE IF NOT EXISTS line_blame(
    ino  BIGINT PRIMARY KEY,
    runs TEXT NOT NULL
);
";

const SQLITE_V1: &str = "
CREATE TABLE IF NOT EXISTS inode(
    ino          INTEGER PRIMARY KEY AUTOINCREMENT,
    kind         TEXT    NOT NULL,
    mode         INTEGER NOT NULL,
    nlink        INTEGER NOT NULL DEFAULT 1,
    size         INTEGER NOT NULL DEFAULT 0,
    content_hash TEXT,
    mtime        INTEGER NOT NULL,
    ctime        INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS dentry(
    parent_ino INTEGER NOT NULL,
    name       TEXT    NOT NULL,
    ino        INTEGER NOT NULL,
    PRIMARY KEY(parent_ino, name)
);
CREATE INDEX IF NOT EXISTS idx_dentry_ino ON dentry(ino);
CREATE TABLE IF NOT EXISTS symlink(
    ino    INTEGER PRIMARY KEY,
    target TEXT NOT NULL
);
";

const POSTGRES_V1: &str = "
CREATE TABLE IF NOT EXISTS inode(
    ino          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind         TEXT   NOT NULL,
    mode         BIGINT NOT NULL,
    nlink        BIGINT NOT NULL DEFAULT 1,
    size         BIGINT NOT NULL DEFAULT 0,
    content_hash TEXT,
    mtime        BIGINT NOT NULL,
    ctime        BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS dentry(
    parent_ino BIGINT NOT NULL,
    name       TEXT   NOT NULL,
    ino        BIGINT NOT NULL,
    PRIMARY KEY(parent_ino, name)
);
CREATE INDEX IF NOT EXISTS idx_dentry_ino ON dentry(ino);
CREATE TABLE IF NOT EXISTS symlink(
    ino    BIGINT PRIMARY KEY,
    target TEXT NOT NULL
);
";
