//! Dual-dialect schema migrations (`docs/DESIGN.md` §4b).
//!
//! One ordered list of migrations, each carrying the SQL for both dialects. Every
//! backend applies the steps it hasn't yet recorded in `schema_meta`, so SQLite
//! and Postgres stay in lockstep from a single source of truth.

/// One migration step, with the SQL for each supported engine.
pub struct Migration {
    pub version: i64,
    pub sqlite: &'static str,
    pub postgres: &'static str,
}

/// The ordered migration list. Append new steps; never edit an applied one.
pub const MIGRATIONS: &[Migration] = &[Migration {
    version: 1,
    sqlite: SQLITE_V1,
    postgres: POSTGRES_V1,
}];

const SQLITE_V1: &str = "
CREATE TABLE IF NOT EXISTS inode(
    ino          INTEGER PRIMARY KEY AUTOINCREMENT,
    kind         TEXT    NOT NULL,
    mode         INTEGER NOT NULL,
    nlink        INTEGER NOT NULL DEFAULT 1,
    size         INTEGER NOT NULL DEFAULT 0,
    content_hash TEXT,
    mtime        INTEGER NOT NULL,
    ctime        INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS dentry(
    parent_ino INTEGER NOT NULL,
    name       TEXT    NOT NULL,
    ino        INTEGER NOT NULL,
    PRIMARY KEY(parent_ino, name)
);
CREATE INDEX IF NOT EXISTS idx_dentry_ino ON dentry(ino);
CREATE TABLE IF NOT EXISTS symlink(
    ino    INTEGER PRIMARY KEY,
    target TEXT NOT NULL
);
";

const POSTGRES_V1: &str = "
CREATE TABLE IF NOT EXISTS inode(
    ino          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind         TEXT   NOT NULL,
    mode         BIGINT NOT NULL,
    nlink        BIGINT NOT NULL DEFAULT 1,
    size         BIGINT NOT NULL DEFAULT 0,
    content_hash TEXT,
    mtime        BIGINT NOT NULL,
    ctime        BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS dentry(
    parent_ino BIGINT NOT NULL,
    name       TEXT   NOT NULL,
    ino        BIGINT NOT NULL,
    PRIMARY KEY(parent_ino, name)
);
CREATE INDEX IF NOT EXISTS idx_dentry_ino ON dentry(ino);
CREATE TABLE IF NOT EXISTS symlink(
    ino    BIGINT PRIMARY KEY,
    target TEXT NOT NULL
);
";
