"""Type stubs for the afs package (re-exported from the ``afs._afs`` extension).

Every I/O method is async (returns an awaitable) so it composes with FastAPI's
`async def` handlers. Structured results are plain ``dict``/``list`` objects,
directly JSON-serializable.
"""
from __future__ import annotations
from typing import Any, Optional

class AfsError(Exception):
    """Base afs error (raised for errors without a more specific mapping)."""

class ConflictError(AfsError):
    """A suggestion's base changed since it was proposed (stale base)."""

class WriteCtx:
    """The actor context to attribute a write to."""
    @staticmethod
    def actor(actor: int) -> "WriteCtx": ...
    @staticmethod
    def session(actor: int, session: int) -> "WriteCtx": ...
    @property
    def actor_id(self) -> int: ...
    @property
    def session_id(self) -> Optional[int]: ...

class Mount:
    """A live FUSE mount; unmounts on ``unmount()``, ``with``-exit, or drop."""
    def unmount(self) -> None: ...
    def __enter__(self) -> "Mount": ...
    def __exit__(self, *args: Any) -> None: ...

class Workspace:
    # --- constructors (async) ---
    @staticmethod
    async def open_local(db_path: str, cas_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_local_packed(db_path: str, data_dir: str, index_dir: str) -> "Workspace": ...
    @staticmethod
    async def open_pg(dsn: str, cas_dir: str) -> "Workspace": ...

    # --- files ---
    async def read(self, path: str) -> bytes: ...
    async def write(self, path: str, data: bytes) -> None: ...
    async def write_as(self, ctx: WriteCtx, path: str, data: bytes) -> None: ...
    async def mkdir_p(self, path: str) -> None: ...
    async def ls(self, path: str) -> list[dict[str, Any]]: ...
    async def stat(self, path: str) -> dict[str, Any]: ...
    async def remove(self, path: str) -> None: ...
    async def rename(self, from_: str, to: str) -> None: ...

    # --- versioning ---
    async def commit(self, author: str, message: str) -> str: ...
    async def log(self) -> list[dict[str, Any]]: ...
    async def status(self) -> list[dict[str, Any]]: ...
    async def diff(self, from_: str, to: str) -> list[dict[str, Any]]: ...
    async def diff_file(self, from_: str, to: str, path: str) -> str: ...
    async def create_branch(self, name: str) -> None: ...
    async def checkout(self, name: str) -> None: ...
    async def branches(self) -> list[dict[str, Any]]: ...
    async def current_branch(self) -> Optional[str]: ...

    # --- attribution ---
    async def create_human(self, name: str, auth_subject: Optional[str] = None) -> int: ...
    async def create_agent(self, name: str, model: str, controller: Optional[int] = None) -> int: ...
    async def create_session(self, actor_id: int, client: Optional[str] = None) -> int: ...
    async def blame(self, path: str) -> list[dict[str, Any]]: ...

    # --- live collaboration ---
    async def watch(self, after_seq: int = 0) -> list[dict[str, Any]]: ...
    async def presence(self, window_secs: int = 60) -> list[dict[str, Any]]: ...
    async def touch(self, actor_id: int, session_id: int, path: Optional[str] = None) -> None: ...

    # --- agent-suggestion review queue ---
    async def suggest(self, ctx: WriteCtx, path: str, data: bytes, summary: Optional[str] = None) -> int: ...
    async def suggest_delete(self, ctx: WriteCtx, path: str, summary: Optional[str] = None) -> int: ...
    async def list_suggestions(self, status: Optional[str] = None, path: Optional[str] = None) -> list[dict[str, Any]]: ...
    async def get_suggestion(self, id: int) -> Optional[dict[str, Any]]: ...
    async def suggestion_diff(self, id: int) -> str: ...
    async def accept_suggestion(self, id: int, approver: WriteCtx) -> None: ...
    async def reject_suggestion(self, id: int, approver: WriteCtx) -> None: ...

    # --- mounting / serving ---
    def mount(self, mountpoint: str) -> Mount: ...
    async def serve_nfs(self, addr: str) -> None: ...

def fuse_mountable() -> bool:
    """Whether a FUSE mount is possible here (``/dev/fuse`` present)."""
    ...
